# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Download CUDA libraries
        uses: Jimver/cuda-toolkit@9b993a72d35b5634a69ca7e34b39a002a87c367c # v0.2.23
        id: cuda-toolkit
        with:
          cuda: '12.6.0'
          sub-packages: '["cudart", "cublas", "cufft"]'

      - name: Copy CUDA libraries
        run: |
          New-Item -Path "$env:TEMP\cuda-libs\" -ItemType Directory -Force
          Write-Host "Cuda install location: $env:CUDA_PATH"
          Push-Location "$env:CUDA_PATH\bin"
          Copy-Item -Path "cufftw64_11.dll", "cublas64_12.dll", "cublasLt64_12.dll", "cudart64_12.dll", "cufft64_11.dll" -Destination "$env:TEMP\cuda-libs\"
          Pop-Location

      - name: Download cuDNN libraries
        run: |
          New-Item -Path "$env:TEMP\cuda-libs\" -ItemType Directory -Force
          Invoke-WebRequest -Uri "https://developer.download.nvidia.com/compute/cudnn/redist/cudnn/windows-x86_64/cudnn-windows-x86_64-9.8.0.87_cuda12-archive.zip" -OutFile "a.zip"
          Expand-Archive -Path "a.zip" -DestinationPath "."
          Push-Location -Path "cudnn-*\bin\"
          Copy-Item -Path "cudnn64_9.dll", "cudnn_adv64_9.dll", "cudnn_cnn64_9.dll", "cudnn_engines_precompiled64_9.dll", "cudnn_engines_runtime_compiled64_9.dll", "cudnn_graph64_9.dll", "cudnn_heuristic64_9.dll", "cudnn_ops64_9.dll" -Destination "$env:TEMP\cuda-libs\"
          Pop-Location

      - name: Check
        run: |
          Get-ChildItem -Path "$env:TEMP\cuda-libs" -Force
